
# Site settings
title: "davidtor.es"
name: "David Tortajada"
subtitle: "Senior Backend Engineer"
email: mail@davidtor.es
phone: +34655579880
url: https://davidtor.es
description: "Senior Java Engineer & IoT Enthusiast"
keywords: "Java & Intershop developer"
meta_author: David Tortajada

minimal_mistakes_skin: "contrast" # Puedes probar: air, mint, sunrise, aqua, dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - .htaccess
  - _pages

exclude:
  - .vscode/
  - .github/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

twitter_username: username
github_username: lomuko

author:
  name     : "David Tortajada"
  avatar   : "/assets/images/me.jpg" 
  bio    : "Senior Java Developer"
  location : "Cantabria, Spain"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/davidtor
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: http://github.com/lomuko
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mail@davidtor.es"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  home-lab:
    output: true
    permalink: /home-lab/:slug/
