# Site settings
title: "DavidTor.es"
name: "David Tortajada"
subtitle: "Senior Backend Engineer"
email: mail@davidtor.es
phone: +34655579880
url: https://davidtor.es
description: "Senior Java Engineer & IoT Enthusiast"
keywords: "Java & Intershop developer"
meta_author: David Tortajada

theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "mint" # Puedes probar: air, mint, sunrise, aqua, dark

# Plugins necesarios
plugins:
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

author:
  name     : "David Tor"
  avatar   : "/assets/images/me.jpg" 
  bio: "Senior Java Engineer"
  location : "Cantabria, Spain"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/davidtor
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: http://github.com/lomuko
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mail@davidtor.es"
  
  # Postal address (add as many lines as necessary)
  address:
    - line: Santander, Cantabria
    - line: CP 39100 - SPAIN
# Google webmaster tools
google_verify: mknHCRGiTdHQ9SRjRiO15_zQeFFllHgknZDpMsDssJY

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 1D8E7E0D0A3BD8571B47891FAAB3B944



# Configuración de contenidos
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: _pages
    values:
      layout: single
      author_profile: true

# Reading Files
include:
  - .htaccess
  - _pages


# Credits content
credits: 
 - Everybody should learn to program a computer because it teaches you how to think. – Steve Jobs

# Build settings
markdown: kramdown
permalink: pretty



exclude:
  - .vscode/
  - .github/