# Site settings
title: Java & Intershop Developer | David Tortajada
brand: Davidtor
email: mail@davidtor.es
phone: +34655579880
url: https://davidtor.es
description: "Freelance Java & Intershop developer for hire, specialising in development B2C and B2B web applications using JavaScript, Node.js & more"
keywords: "David Tortajada - Freelance Java & Intershop Developer"
skills: "Java & Intershop Developer"
meta_author: David Tortajada

# Google webmaster tools
google_verify: mknHCRGiTdHQ9SRjRiO15_zQeFFllHgknZDpMsDssJY

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 1D8E7E0D0A3BD8571B47891FAAB3B944

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: David Tortajada
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/davidtor
  - title: github
    url: http://github.com/lomuko

# Postal address (add as many lines as necessary)
address:
  - line: Santander, Cantabria
  - line: CP 39100 - SPAIN

# Credits content
credits: 
 - Everybody should learn to program a computer because it teaches you how to think. – Steve Jobs

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

exclude:
  - .vscode/
  - .github/